#!/usr/bin/env node

var path = require("path"),
    minimist = require("minimist"),
    esperanto = require("esperanto");

var polyfill = {
  "Map":
      'if (!this.Map) {\n' +
      '  Map = function() {};\n' +
      '  Map.prototype = {\n' +
      '    set: function(k, v) { this["$" + k] = v; return this; },\n' +
      '    get: function(k) { return this["$" + k]; },\n' +
      '    has: function(k) { return "$" + k in this; }\n' +
      '  };\n' +
      '}\n' +
      '\n'
};

var argv = minimist(process.argv.slice(2)),
		name = argv.name,
		input = "./src/" + argv._[0],
		prologue = argv["polyfill-map"] ? polyfill.Map : "";

var banner =
    ( argv["polyfill-map"] ? polyfill.Map : "" ) +
    'this.d3 || this.d3 = {};\n\n';

esperanto.bundle({
  entry: input
}).then(function(bundle) {
  process.stdout.write(bundle.toUmd({
    name: name,
	indent: "  ",
    banner: banner,
    strict: true
  }).code);
}).catch(function(error) {
  console.error(error);
});
